version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: dashboard
      TZ: Asia/Taipei
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres:
